### ISSUE TITLE
打包后META-INF里的文件名被改名了

### ISSUE THREAD

**Issue by onexuan** [Bilibili/apk-channelization#1]
我用eclipse 打包APK，META-INF文件夹里的会生成CERT.SF与CERT.RSA，但用python打包后META-INF里的文件名被改名了，变成了用keyalias作为文件名了，比如我的keyalias是xxxxx 改后变成了XXXXX.SF和XXXXX.RSA 

如何不让其改名。

**Comment by onexuan** [comment]
已解决 找到参数

**Comment by javalue** [comment]
@onexuan 能告知在哪里修改吗？
